### PR TITLE
W22 5pm 4 jz sk kd AdminEditPage for edit commons

### PR DESCRIPTION
**Pull request by zjw9635468**
# Overview

Add AdminEditPage for admin to edit a specific common

# Issues Addressed

#18

# Details

For admins, they can view all commons in a page and there are delete button and edit button for each row of commons.
- we make the AdminEdidPage for the edit function and can be navigated by click the edit button on AdminCommonPage. 
- In AdminEditPage, the buckets are prefilled by the original value. Admin are free to change any of them.
- we add storybook for AdminEditPage

### CODE REVIEW

**Review by agweiyu — DISMISSED** [review]
Edit page is working as intended, LGTM ~provided that mutation testing passes~

**Review by samar1409 — DISMISSED** [review]
LGTM

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
