### PR TITLE
changed common controller delete return JSON instead of string

### PR DESCRIPTION
**Pull request by jasonem225**
# Overview

I will be changing the commons controller delete returns from string to JSON.

# Issues Addressed

#53 

# Details

I have currently changed the output for the commons delete controller from string to JSON and got the tests to pass. I will make more pull requests for other parts of the controller.

### CODE REVIEW

**Comment by agweiyu** [comment]
Did something come up when editing the output of the edit endpoint? I'll take a look and see if the failing check can be resolved with a pull from main

**Comment by jasonem225** [comment]
The output for the controller becomes a JSON for only the delete right now. When I tried doing the same for edit, said the code coverage fell, so was trying to find, but kind of confused since all I did was change the output from string to JSON. For calling the toast, we might need to change the onDeleteSuccess, which takes the output (previously a string) and showed it as toast. If we change to controller output to JSON, we will probably need to change the output from message to something like message.message

**Comment by agweiyu** [comment]
If I were to guess the coverage issue was bc this branch fell behind main. It's worth trying again to see if the check will pass

I'll take a look at the toast

**Review by samar1409 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
