### PR TITLE
W22 5pm 4 je new backend common controller routes tests

### PR DESCRIPTION
**Pull request by jasonem225**
# Overview

Added additional tests for commons controller concerning user authorization, such as checking if a logged out user can access functions that only logged in users/admins can use, such as join common, and checks logged in users cannot use admin functions, such as edit or delete

# Issues Addressed

#45 

- [x] add logged out checks, cannot use user/admin endpoints
- [x] add user checks, cannot use admin endpoints

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
This PR has a title of "Controller additional tests test" .... but that is misleading.

This PR does not just add new tests.  It also adds new backend controller routes.

Those should be mentioned in the title, and explained in the description.

**Review by zjw9635468 — APPROVED** [review]
Looks good to merge!

**Review by pconrad — CHANGES_REQUESTED** [review]
For this PR, I think the description could be a bit more accurate:

Current: 

Title: `new backend common controller routes`

Description:
```
Additional tests for commons controller concerning user authorization, such as checking if a logged out user can access functions that only logged in users/admins can use, such as join common, and checks logged in users cannot use admin functions, such as edit or delete
```

But... it actually does a lot more than add tests.  And "add controller routes" is pretty vague.
Routes that do what?
It appears, from a causal read, that it:
* adds  new body parameters to the POST method for creating a commons
* adds PUT and DELETE routes for edit /deleting of commons by admin users
* adds a starting date to the commons
* etc...  (I'm leaving some work for you)

That's the kind of detail that we need in a PR description so that someone can effectively code review it, and QA the changes to the code.

Can someone hop on that?

**Comment by agweiyu** [comment]
Converting this PR to [PR 72](https://github.com/ucsb-cs156-w22/team04-w22-5pm-HappyCows/pull/72) to clarify the scope of changes here, as the additions 

> * adds  new body parameters to the POST method for creating a commons
> * adds PUT and DELETE routes for edit /deleting of commons by admin users
> * adds a starting date to the commons
> * basic tests for the post/put/delete commons routes

were introduced in [PR 30](https://github.com/ucsb-cs156-w22/team04-w22-5pm-HappyCows/pull/30)

**Pull request closed without merging**
