### PR TITLE
W22 5pm 4 jz kd create edit common form for edit page

### PR DESCRIPTION
**Pull request by zjw9635468**
# Overview

Add edit common component

# Issues Addressed

#18

# Details

For admins, they can view all commons in a page and there are delete button and edit button for each row of commons.
- In this pull request, we make the editCommonForm for the edit function.
- Because for editing a common, we cannot change the starting date, so we create another form for editing.
- The edit button would link to a empty page because the EditPage is done by next pull request. But you can check the form on storybook.
-  we add storybook for editCommonForm

### CODE REVIEW

**Review by samar1409 — DISMISSED** [review]
LGTM

**Comment by agweiyu** [comment]
https://team04-w22-5pm-4-qa.herokuapp.com/admin/editcommons/13

~Not seeing the edit form when deployed to heroku atm, needs a look~

Disregard, I was mistaken on what this PR addresses

**Review by agweiyu — DISMISSED** [review]
Components are looking good on storybook. LGTM

**Review by samar1409 — DISMISSED** [review]
LGTM

**Review by kdeng23 — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM.  I will note that instead of making a separate form for editing that didn't have the date on it, I would have probably just made the date either appear, or not based on whether you passed in a callback for creating, or a callback for editing.

We have an example of that in STARTER code from previous assignments; it keeps the code more DRY (Don't Repeat Yourself.)

But this is ok.

**Pull request merged**
