### PR TITLE
w22 5pm 4 refresh on logout

### PR DESCRIPTION
**Pull request by jasonem225**
# Overview

Working on log out. When logging out, trying to make join and visit buttons disappear. Also trying to make joined commons disappear as well. 

# Issues Addressed

#53 

# Details

Currently just made it so that when log out button is clicked, the page is refreshed so the commons and buttons for commons disappear. Thinking about whether to try and make commons (not the joined commons) visible even when user is logged out, but not give any clickable buttons

### CODE REVIEW

**Comment by jasonem225** [comment]
I used an href inside the logout button so that when the user clicks the log out button, the page would refresh and no longer how the commons or buttons.

**Comment by jasonem225** [comment]
I used an href inside the logout button so that when the user clicks the log out button, the page would refresh and no longer how the commons or buttons.

**Comment by agweiyu** [comment]
nit added 5pm-4 to the title of this PR
Feature is working as intended on heroku, LGTM!

**Review by agweiyu — DISMISSED** [review]
nit added 5pm-4 to the title of this PR
Feature is working as intended on heroku, LGTM!

**Review by zjw9635468 — DISMISSED** [review]
LGTM

**Comment by agweiyu** [comment]
merge resolve seems to have failed bc of an unresolved import, looking into it

**Comment by agweiyu** [comment]
Page is refreshing on logout with appnavbar being consistent with main now

**Review by zjw9635468 — APPROVED** [review]
Checked on Heroku, the functionality works. LGTM!

**Pull request merged**
