### PR TITLE
W22 5pm 3 ig add current day and endingDate to commons overview frontend

### LINKED ISSUE #67: Set up CommonsOverview Frontend
The `CommonsOverview` component should display information from the current Commons. The `Commons` entity should be updated to support storing and providing this information.

#### Frontend:
- [x] Update CreateCommonsForm.js to have user type in duration of game (used for calculating end date)
- [x] Update CommonsOverview.js to calculate end date and current day of game
- [x] Improve npm run coverage
- [x] Improve mutation testing: npx stryker run for commonsOverview.test.js

### PR DESCRIPTION
**Pull request by isaiahgarcia**
# Overview

This PR creates the frontend visualization for CommonsOverview.js by specifying the current day and the endingDate. This PR is an improvement to the last PR that I made (W22 5pm 3 ig add current day and end date to commons overview). Unfortunately, I found out that I needed to get rid of my moment library, and use java's date library tools. This set me back and I was in a rush, forcing me to not reach 100% coverage and mutation test (though they are close). 

# Issues Addressed
#67 

# Details
Coverage:
Screen Shot 2022-03-11 at 5 13 04 PM

Mutation Testing:
Screen Shot 2022-03-11 at 5 12 06 PM

### CODE REVIEW

**Review by nguglielmin — COMMENTED** [review]
this PR somehow includes every file in the repo which makes it difficulty to thoroughly review. I'm guessing the focus is on `commonsOverview.js` so I'm just going to look at the changes made there. Let me know if there are other files i need to review more closely.

**Review by nguglielmin — APPROVED** [review]
LGTM!
I'm pleased that this will fix the "Today is day __" component on the PlayPage. Should make the UI more appealing.

**Review by nguglielmin — DISMISSED** [review]
still lgtm ... accidentally re-requested a review from myself

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
